name: 检查链接有效性 - 拆 - 安装程序
on:
  workflow_dispatch:
  #schedule: [{ cron: 0 0 * * * }]

jobs:
  Remove:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdirectory: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        env:
          PYTHONIOENCODING: utf-8
        with:
          python-version: '3.x'

      - name: 克隆 winget-pkgs fork
        run: |
          git clone "https://github.com/DuckDuckStudio/winget-pkgs" -b "wingettools" --depth 1

      - name: 安装依赖
        env:
          PYTHONIOENCODING: utf-8
        run: pip install -r "environment/requirements.txt"

      - name: 执行检查
        env:
          PYTHONIOENCODING: utf-8
        run: python "auto_script/check/checker-拆-安装程序.py" ${{ matrix.subdirectory }}
