name: 检查链接有效性 - 拆
on:
  workflow_dispatch:
    inputs:
      fail_level:
        type: choice
        description: "失败等级"
        required: true
        default: "error"
        options:
          - error
          - warning
      branch:
        description: "检查的分支"
        required: true
        default: "master"
      fork:
        description: "检查的 fork 仓库的所有者"
        required: true
        default: "microsoft"
      mode:
        type: choice
        description: "生成模式"
        required: true
        default: "Release"
        options:
          - Release
          - Debug

jobs:
  Check-installers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        subdirectory: ["1", "2", "3", "4", "5", "6", "7", "8", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 克隆 winget-pkgs fork
        run: |
          # 克隆对应的 fork 和对应的分支
          git clone "https://github.com/${{ github.event.inputs.fork }}/winget-pkgs" "winget-pkgs" -b ${{ github.event.inputs.branch }} --depth 1

      - name: 恢复依赖
        run: dotnet restore auto_script/check/checker/checker.csproj

      - name: 编译项目
        run: dotnet build auto_script/check/checker/checker.csproj --configuration ${{ github.event.inputs.mode }}

      - name: 执行检查
        run: dotnet run --project "auto_script/check/checker/checker.csproj" -- ${{ matrix.subdirectory }} ${{ github.event.inputs.fail_level }}
