name: 获取安装程序文件

on:
  workflow_dispatch:
    inputs:
      file:
        description: '需要获取的文件 URL'
        required: true
      file_type:
        description: '文件的后缀名'
        required: false

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: 提取文件扩展名
      id: extract_extension
      run: |
        url="${{ github.event.inputs.file }}"
        specified_extension="${{ github.event.inputs.file_type }}"

        # 如果用户指定了文件类型，则使用指定的类型
        if [ -n "$specified_extension" ]; then
          extension="$specified_extension"
        else
          # 否则从 URL 中提取扩展名
          extension="${url##*.}"

          # 如果 URL 中没有扩展名，则默认使用 .exe
          if [ "$extension" == "$url" ]; then
            extension="exe"
          fi
        fi

        echo "file_extension=$extension" >> $GITHUB_ENV

    - name: 下载文件
      run: |
        # 使用提取或指定的扩展名下载文件
        wget ${{ github.event.inputs.file }} -O installer.${{ env.file_extension }}

    - name: 获取 SHA256
      run: echo "sha256=$(sha256sum installer.${{ env.file_extension }} | awk '{ print \$1 }')" >> $GITHUB_ENV

    - name: 上传获取的文件
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: installer.${{ env.file_extension }}

    - name: 输出 SHA256
      run: |
        echo "SHA256: ${{ env.sha256 }}"

    - name: 设置 Rust
    # 用于后续的 `cargo binstall` 安装
      uses: cargo-bins/cargo-binstall@main
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 安装 Komac
      run: cargo binstall komac -y
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 分析安装程序
      run: komac analyse installer.${{ env.file_extension }}
