name: 获取安装程序文件

on:
  workflow_dispatch:
    inputs:
      file:
        description: '需要获取的文件 URL'
        required: true
      file_type:
        description: '文件的后缀名'
        required: false

permissions:
  contents: read

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: 提取文件扩展名
      id: extract_extension
      shell: bash
      env:
        GITHUB_EVENT_INPUTS_FILE: ${{ github.event.inputs.file }}
        GITHUB_EVENT_INPUTS_FILE_TYPE: ${{ github.event.inputs.file_type }}
      run: |
        url="${GITHUB_EVENT_INPUTS_FILE}"
        specified_extension="${GITHUB_EVENT_INPUTS_FILE_TYPE}"

        # 如果用户指定了文件类型，则使用指定的类型
        if [ -n "$specified_extension" ]; then
          extension="$specified_extension"
        else
          # 否则从 URL 中提取扩展名
          extension="${url##*.}"

          # 如果 URL 中没有扩展名，则默认使用 .exe
          if [ "$extension" == "$url" ]; then
            extension="exe"
          fi
        fi

        echo "file_extension=$extension" >> $GITHUB_ENV

    - name: 下载文件
      shell: bash
      env:
        GITHUB_EVENT_INPUTS_FILE: ${{ github.event.inputs.file }}
      run: wget "${GITHUB_EVENT_INPUTS_FILE}" -O "installer.${FILE_EXTENSION}"

    - name: 获取 SHA256
      # tr 用于将小写字母转换为大写字母
      shell: bash
      run: |-
        echo "sha256=$(sha256sum 'installer.${FILE_EXTENSION}' | tr 'a-f' 'A-F')" >> $GITHUB_ENV
        sha256sum "installer.${FILE_EXTENSION}" | tr 'a-f' 'A-F'

    - name: 上传获取的文件
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        archive: false
        path: installer.${{ env.file_extension }}
        retention-days: 1

    - name: 设置 Rust
      # 用于后续的 `cargo binstall` 安装
      uses: cargo-bins/cargo-binstall@0b24824336e2b3800b0f89d9e08b2c08bfa3dcdd # v1.17.9
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 安装 Komac
      run: cargo binstall komac -y
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 分析安装程序
      run: |-
        file "installer.${FILE_EXTENSION}"
        komac analyse "installer.${FILE_EXTENSION}" --hash
