name: 不修改的更新清单

on:
  workflow_dispatch:
    inputs:
      id:
        description: 软件包标识符
        required: true
      ver:
        description: 软件包版本
        required: true
      urls:
        description: 软件包安装程序链接
        required: true
      issue:
        description: 解决的 Issue
        required: false
      submit:
        type: boolean
        description: 提交更新
        required: true
        default: true

jobs:
  komac-update:
    runs-on: ubuntu-latest

    steps:
    - name: 设置 Rust
    # 用于后续的 `cargo binstall` 安装
      uses: cargo-bins/cargo-binstall@main
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 安装 Komac
      run: cargo binstall komac -y
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: 更新清单
      env:
        KOMAC_FORK_OWNER: "DuckDuckStudio"
        GITHUB_TOKEN: ${{ secrets.WINGET_PKGS_TOKEN }}
      run: |-
        if [ ${{ github.event.inputs.submit }} = true ]; then
          if [ -n "${{ github.event.inputs.issue }}" ]; then
            komac update ${{ github.event.inputs.id }} --version ${{ github.event.inputs.ver }} --urls ${{ github.event.inputs.urls }} --created-with "@DuckDuckStudio's Automation" --created-with-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --submit --resolves ${{ github.event.inputs.issue }}
          else
            komac update ${{ github.event.inputs.id }} --version ${{ github.event.inputs.ver }} --urls ${{ github.event.inputs.urls }} --created-with "@DuckDuckStudio's Automation" --created-with-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --submit
          fi
        else
          komac update ${{ github.event.inputs.id }} --version ${{ github.event.inputs.ver }} --urls ${{ github.event.inputs.urls }} --created-with "@DuckDuckStudio's Automation" --created-with-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" --dry-run
        fi
